quotes/app_quotes/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import AuthorDetailView

app_name = "app_quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('author/<int:pk>/', AuthorDetailView.as_view(), name='author_detail'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app_quotes.urls")),
    path("users/", include("users.urls")),
]

quotes/users/urls.py
from django.contrib import admin

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("signin/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/app_quotes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'fullname'], name='unique fullname')
        ]

    def __str__(self):
        return f"{self.fullname}:"


class Tag(models.Model):
    tag = models.CharField(max_length=50, null=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['tag'], name='unique tag')
        ]

    def __str__(self):
        return f"{self.tag}:"


class Quote(models.Model):
    description = models.CharField(max_length=5000, null=False)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    tag = models.ManyToManyField(Tag, through='QuoteTag')

    def __str__(self):
        return f"{self.description}:"


class QuoteTag(models.Model):
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    class Meta:
        db_table = 'quote_tag'


class AuthorDetail(models.Model):
    user = models.OneToOneField(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.fullname

quotes/app_quotes/forms.py
from django import forms
from django.forms import ModelForm, CharField, TextInput
from .models import Author, Quote, Tag


class AuthorForm(ModelForm):

    fullname = CharField(min_length=5, max_length=50, required=True, widget=TextInput())

    class Meta:
        model = Author
        fields = ['fullname']


class QuoteForm(ModelForm):
    description = CharField(min_length=10, max_length=500, required=True, widget=TextInput())

    class Meta:
        model = Quote
        fields = ['description']
        exclude = ['authors', 'tags']


class TagForm(ModelForm):
    tag = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['tag']

quotes/app_quotes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic import DetailView

from .forms import AuthorForm, QuoteForm, TagForm
from .models import Author, Quote, Tag


# Create your views here.


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'app_quotes/author_detail.html'
    context_object_name = 'author'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        quotes = Quote.objects.filter(author=self.object).all()
        context['quotes'] = quotes
        return context


def main(request):
    quotes = Quote.objects.all()
    return render(request, 'app_quotes/index.html', {"quotes": quotes,
                                                     "title": "Quotes:",
                                                     })


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save(commit=False)
            new_author.user = request.user
            new_author.save()
            return redirect(to='app_quotes:root')
        else:
            return render(request, 'app_quotes/author.html', {'form': form})

    return render(request, 'app_quotes/author.html', {'form': AuthorForm()})


@login_required
def quote(request):
    authors = Author.objects.all()
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            choice_aut = Author.objects.filter(fullname__in=request.POST.getlist('authors'))
            new_quote.author = choice_aut.first()
            new_quote.save()
            choice_tag = Tag.objects.filter(tag__in=request.POST.getlist('tags'))
            for tag_ in choice_tag.iterator():
                new_quote.tag.add(tag_)
            new_quote.save()

            return redirect(to='app_quotes:root')
        else:
            return render(request, 'app_quotes/quote.html', {"authors": authors, 'form': form, "tags": tags})

    return render(request, 'app_quotes/quote.html', {"authors": authors, 'form': QuoteForm(), "tags": tags})


@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag_ = form.save(commit=False)
            tag_.user = request.user
            tag_.save()
            return redirect(to='app_quotes:root')
        else:
            return render(request, 'app_quotes/tag.html', {'form': form})

    return render(request, 'app_quotes/tag.html', {'form': TagForm()})

quotes/app_quotes/templates/app_quotes/author.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>Add Author</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Fullname</label>
            {{form.fullname}}
        </div>
        <span>{{form.errors.fullname}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Add new author</button>
</form>
{% endblock %}

quotes/app_quotes/templates/app_quotes/author_detail.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>{{title}}</h1>
<div>
    <span>Name: {{ author.fullname }}</span>
    <br>
    <span>User: {{ author.user.username }}</span>
    </br>
    <br>
    {% for quote in quotes %}
    <br>
    <span>Quotes: {{ quote.description }}</span>
    </br>
    {% endfor %}
    </br>
</div>
{% endblock %}

quotes/app_quotes/templates/app_quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_quotes/style.css' %}">
    <title>{{title}}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:author' %}">Add Author</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:quote' %}">Add Quote</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app_quotes:tag' %}">Add Tag</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">SignIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">SignUp</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

quotes/app_quotes/templates/app_quotes/index.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>{{title}}</h1>
<div>
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <h4><a href="{% url 'app_quotes:author_detail' pk=quote.author.pk %}" role="button" class="secondary">{{quote.author.fullname}}</a></h4>
        <p>{{quote.description}}</p>
        <div>
            {% for tag in quote.tag.all %}
            <a class="tag" href="#">{{tag.tag}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

quotes/app_quotes/templates/app_quotes/quote.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>Add Quotes</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Description</label>
            {{form.description}}
        </div>
        <span>{{form.errors.description}}</span>
        <div style="padding: 10px">
            <label> Select authors:
                <select name="authors" multiple="multiple" required>
                    {% for author in authors %}
                    <option value="{{author.fullname}}">{{author.fullname}}</option>
                    {% endfor %}
                </select>
            </label>
        </div>
        <div style="padding: 10px">
            <label> Select tags:
                <select name="tags" multiple="multiple" required>
                    {% for tag in tags %}
                    <option value="{{tag.tag}}">{{tag.tag}}</option>
                    {% endfor %}
                </select>
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Add new quotes</button>
</form>
{% endblock %}

quotes/app_quotes/templates/app_quotes/tag.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>Add Tag</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Tag:</label>
            {{form.tag}}
        </div>
        <span>{{form.errors.tag}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Add new tag</button>
</form>
{% endblock %}