quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app_quotes.urls")),
    path("users/", include("users.urls")),
]

quotes/users/urls.py
from django.contrib import admin

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("signin/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/users/models.py
from django.db import models

# Create your models here.

quotes/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=150, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=12, min_length=8, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")

quotes/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm


# Create your views here.


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="app_quotes:root")
        return super(RegisterView, self).dispatch(request, * args, ** kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f'Вітаю {username}. Ваш аккаунт успішно створено')
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": form})

quotes/users/templates/users/logout.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>Goodbye!</h1>
{% endblock %}

quotes/users/templates/users/password_reset.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_complete.html
{% extends "app_quotes/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

quotes/users/templates/users/password_reset_confirm.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

quotes/users/templates/users/password_reset_done.html
{% extends "app_quotes/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

quotes/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

quotes/users/templates/users/signin.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>SignUp</h1>

<!-- Виводимо Flash сповіщення-->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<!--Обробляємо помилки форми які не відносяться до полів -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.non_field_errors}}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
    <button type="submit" class="btn btn-primary">Sing In</button>
</form>
{% endblock %}

quotes/users/templates/users/signup.html
{% extends "app_quotes/base.html" %}

{% block content %}
<h1>SignUp</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">First Name</label>
            {{form.first_name}}
        </div>
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Last Name</label>
            {{form.last_name}}
        </div>
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Confirm password</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sing Up</button>
</form>
{% endblock %}